// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Thu Jun 15 15:45:50 2023

FFT_Module FFT_Module_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.in_signal_re(in_signal_re_sig) ,	// input [7:0] in_signal_re_sig
	.in_signal_im(in_signal_im_sig) ,	// input [7:0] in_signal_im_sig
	.real_power(real_power_sig) ,	// output [7:0] real_power_sig
	.imag_power(imag_power_sig) ,	// output [7:0] imag_power_sig
	.exp_power(exp_power_sig) ,	// output [5:0] exp_power_sig
	.fft_source_sop(fft_source_sop_sig) ,	// output  fft_source_sop_sig
	.fft_source_eop(fft_source_eop_sig) ,	// output  fft_source_eop_sig
	.sink_sop(sink_sop_sig) ,	// output  sink_sop_sig
	.sink_eop(sink_eop_sig) ,	// output  sink_eop_sig
	.sink_valid(sink_valid_sig) ,	// output  sink_valid_sig
	.source_valid(source_valid_sig) ,	// output  source_valid_sig
	.source_ready(source_ready_sig) ,	// input  source_ready_sig
	.source_error(source_error_sig) ,	// output [1:0] source_error_sig
	.reset_n(reset_n_sig) 	// input  reset_n_sig
);

